name: Get_ARM_Host
on: workflow_dispatch # Kích hoạt bằng tay cho an toàn

jobs:
  arm-job:
    runs-on: ubuntu-24.04-arm64 # ĐÂY LÀ CHÌA KHÓA: Máy ARM thật của GitHub
    steps:
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 360 # Bạn có 6 tiếng sử dụng miễn phí mỗi lần chạy
