name: Get_ARM_Host
on: workflow_dispatch

jobs:
  arm-job:
    runs-on: ubuntu-22.04-arm64 # Đổi sang 22.04 cho ổn định và nhanh có máy
    steps:
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 350 # Treo gần 6 tiếng
